spring:
  application:
    name: api-bird-orchestator-microservice
  r2dbc:
    url: r2dbc:postgresql://${DB_LANDSCAPE_HOST:localhost}:${DB_LANDSCAPE_PORT:5433}/${DB_LANDSCAPE_NAME:bird_dex}
    username: ${DB_LANDSCAPE_USER:bird_user}
    password: ${DB_LANDSCAPE_PASSWORD:bird_pass}
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

aws:
  s3:
    bucket: ${AWS_S3_BUCKET_NAME:}
    url: ${AWS_S3_URL:}
    access-key: ${AWS_S3_ACCESS_KEY:}
    secret-key: ${AWS_S3_SECRET_KEY:}
