spring:
  application:
    name: api-bird-orchestator-microservice
  r2dbc:
    url: r2dbc:postgresql://${DB_BIRD_DEX_HOST:localhost}:${DB_BIRD_DEX_PORT:5432}/${DB_BIRD_DEX_NAME:bird_dex}
    username: ${DB_BIRD_DEX_USER:bird_user}
    password: ${DB_BIRD_DEX_PASSWORD:bird_password}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:user}
    password: ${RABBITMQ_PASSWORD:password}
    virtual-host: /
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

aws:
  s3:
    bucket: ${AWS_S3_BUCKET_NAME:}
    access-key: ${AWS_S3_ACCESS_KEY:}
    secret-key: ${AWS_S3_SECRET_KEY:}

cleanup:
  rejected-images:
    fixed-delay-ms: ${CLEANUP_REJECTED_IMAGES_FIXED_DELAY_MS:3600000}

rabbitmq:
  exchange: bird_detection.exchange
  queue: bird_detection.pending.queue
  routing-key: bird_detection.pending
  result-queue: bird_detection.resultado.queue
  result-routing-key: bird_detection.result
  classification-routing-key: bird_classification.pending
  classification-queue: bird_classification.queue
  result-classification-routing-key: bird_classification.result
  classification-result-queue: bird_classification.result.queue
